name: Deploy to cloudtype
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: gameto/gameto
          stage: dev
          yaml: >
            name: seb41-main-033

            app: java@11

            options:
              ports: 8080
              env:
                - name: DB_HOST
                  value: mariadb
                - name: DB_PORT
                  value: "3306"
                - name: DB_NAME
                  value: gameto
                - name: MYSQL_USERNAME
                  value: root
                - name: MYSQL_PASSWORD
                  value: gameto134652!!
                - name: REDIS_HOST
                  value: redis
                - name: REDIS_PORT
                  value: "6379"
                - name: REDIS_PASSWORD
                  value: gametoredis!!
                - name: MAX_FILE_SIZE
                  value: 50MB
                - name: MAX_REQUEST_SIZE
                  value: 50MB
                - name: JWT_SECRET_KEY
                  value: kevin12341234123412341234123412341234adsfgeeettwaeaafasfsadf
                - name: ACCESS_TOKEN_EXPIRATION_MINUTES
                  value: "20"
                - name: REFRESH_TOKEN_EXPIRATION_MINUTES
                  value: "3600"
                - name: ACCESS_KEY
                  value: AKIA43WTYU3A4JUX2EX4
                - name: SECRET_KEY
                  value: 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
                - name: REGION
                  value: ap-northeast-2
                - name: SPRING_PROFILES_ACTIVE
                  value: staging
                - name: TZ
                  value: Asia/Seoul
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
