INSERT INTO game_db VALUES (1, 'League of Legends', '리그 오브 레전드');
INSERT INTO game_db VALUES (2, 'VALORANT', '발로란트');
INSERT INTO game_db VALUES (3, 'OVERWATCH 2', '오버워치 2');
INSERT INTO game_db VALUES (4, 'LostArk', '로스트아크');
INSERT INTO game_db VALUES (5, 'MapleStory', '메이플스토리');
INSERT INTO game_db VALUES (6, 'SuddenAttack', '서든어택');
INSERT INTO game_db VALUES (7, 'PUBGs BattleGround', '배틀그라운드');
INSERT INTO game_db VALUES (8, 'Dungeon & Fighter', '던전앤파이터');
INSERT INTO game_db VALUES (9, 'CYPHERS', '사이퍼즈');
INSERT INTO game_db VALUES (10, 'Minecraft', '마인크래프트');
INSERT INTO game_db VALUES (11, 'Diablo II', '디아블로 2');
INSERT INTO game_db VALUES (12, 'Diablo III', '디아블로 3');
INSERT INTO game_db VALUES (13, 'Among Us', '어몽어스');
INSERT INTO game_db VALUES (14, 'Final Fantasy XIV', '파이널 판타지 14');
INSERT INTO game_db VALUES (15, 'Eternal Return', '이터널 리턴');
INSERT INTO game_db VALUES (16, 'Steam Game', '스팀 게임');
INSERT INTO game_db VALUES (17, 'Nintendo Game', '닌텐도 게임');
INSERT INTO game_db VALUES (18, 'ETC', '기타');
ALTER TABLE LIKES ADD UNIQUE INDEX (USER_BOARD_ID, MEMBER_ID);
ALTER TABLE LIKES ADD UNIQUE INDEX (COMMENT_ID, MEMBER_ID);
